status = [
    # GitHub Actions
    "ci",
    # Cirrus CI
    "test (aarch64-unknown-linux-gnu)",
    "test (aarch64-unknown-linux-gnu, glibc 2.17)",
    "test (aarch64-unknown-linux-musl)",
    "test (aarch64-apple-darwin)",
    "valgrind (aarch64-unknown-linux-gnu)",
]
timeout_sec = 10800
