[package]
name = "portable-atomic-internal-codegen"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1"
bindgen = "0.63"
camino = "1"
duct = "0.13"
fs-err = "2"
ignore = "0.4"
indexmap = { version = "1", features = ["std"] }
prettyplease = "0.1"
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.24", features = ["derive"] }
syn = { version = "1", features = ["full"] }
