[package]
name = "portable-atomic-internal-codegen"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1"
bindgen = "0.65"
camino = "1"
duct = "0.13"
fs-err = "2"
globset = "=0.4.9" # globset 0.4.10 depends on bstr 1 which may cause https://github.com/rust-lang/cargo/issues/10623
prettyplease = "0.2"
proc-macro2 = "1"
quote = "1"
regex = "~1.8" # regex 1.8 may cause https://github.com/rust-lang/cargo/issues/10623
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = { version = "2", features = ["full"] }
